apiVersion: apps/v1
kind: Deployment
metadata:
  name: stashcache-cache-deployment
spec:
  selector:
    matchLabels:
      app: stashcache-cache
  template:
    metadata:
      labels:
        app: stashcache-cache
    spec:
      containers:
        - name: stashcache-cache
          image: slateci/stashcache:latest
          ports:
            - containerPort: 1094
      volumes:
        - name: stashcache-data
          emptydir: {}
