kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/export/k8s_2"
    server: 192.170.227.3
