kind: Service
apiVersion: v1
metadata:
  name: stashcache-service
spec:
  type: NodePort
  selector:
    app: stashcache
  ports:
  - protocol: TCP
    name: xrootd
    port: 1094
    targetPort: 1094
    nodePort: 31094
    #   externalIPs:
    # - 192.170.227.231

---
