kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stashcache-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
